#!/usr/bin/env bash
set -euo pipefail

# Deploys blinklabs-io/vpn-contracts onto the ephemeral testnet generated by
# the configurator service, then writes out the addresses/policy IDs
# vpn-indexer needs to observe and build transactions against them.
#
# Mirrors the deploy sequence in vpn-contracts/scripts (01-mint-admin-nft.sh
# in particular), adapted to run unattended against a network we just
# created rather than an existing preview/preprod deployment: this script
# also has to *apply* the two validators' constructor parameters (the
# preview/preprod .plutus files ship pre-applied for those networks'
# addresses, which we don't have here) - see plutus_json_to_cbor.py for why.

TESTNET_MAGIC="${TESTNET_MAGIC:?TESTNET_MAGIC is required}"
MAGIC_ARG="--testnet-magic ${TESTNET_MAGIC}"
export CARDANO_NODE_SOCKET_PATH="${CARDANO_NODE_SOCKET_PATH:-/ipc/node.socket}"

GENESIS_DIR="${GENESIS_DIR:-/genesis}"
OUT_DIR="${OUT_DIR:-/shared}"
WALLET_DIR="${OUT_DIR}/wallets"
WORK_DIR="/work"
BLUEPRINT="${WORK_DIR}/plutus.json"

# Reference data offered by the deployed instance. Durations are
# milliseconds (VPNData.expiration_time is a unix-ms timestamp).
REGION_HEX="757320656173742d31" # "us east-1" - the WireGuard-mode vpn-indexer's region
PRICE_LOVELACE=5000000
# The OpenVPN region (the second, OpenVPN-mode vpn-indexer instance - see
# testnet.sh's own apply_vpn_indexer_openvpn) - a second, distinct region
# minted into the same reference datum below rather than replacing
# "us east-1" above, so existing wireguard-only tests are
# unaffected. Hex-computed at runtime instead of hand-typed like the region
# above, to remove that error class for a value that's easy to get wrong.
OPENVPN_REGION="${DEVNET_OPENVPN_REGION:-eu west-1}"
OPENVPN_REGION_HEX=$(printf '%s' "${OPENVPN_REGION}" | od -An -tx1 | tr -d ' \n')
# Must stay >= 1 hour (3_600_000ms): the frontend's normalizeDurationMs()
# (src/pages/Account.tsx) treats any duration below that as a value given in
# seconds rather than ms and multiplies it by 1000 to "fix" it - a heuristic
# for an API unit ambiguity that never applies to real (hour+) subscription
# plans, but silently corrupts a genuinely-short one like a 3-minute test
# fixture, producing a duration that no longer exact-matches this refdata
# and gets rejected by vpn-indexer's determinePlanSelection(). purchase-flow
# spec.ts drives this UI directly and hits exactly that if this dips below
# the threshold.
DURATION_MS=7200000 # 2 hours - no test relies on actual short-lived expiry
WAIT_TIME_MS=0       # grace period after expiry before a client can be burned

log() { echo "[deploy] $*" >&2; }

# Idempotency guard: testnet.sh's own cluster_up() always deletes and
# recreates the whole cluster fresh, so this Job normally never runs twice
# against the same volumes - but a manual re-apply of just this one Job
# against an already-deployed cluster (debugging, or re-running one phase
# in isolation) would hit `/work/plutus.json` already fully-applied from
# the earlier run (every validator has zero parameters left to apply), and
# `aiken blueprint apply` fails outright. The genesis/chain state backing
# the earlier run's addresses is still there regardless, so there's
# nothing to redo.
if [ -f "${OUT_DIR}/.deployed" ]; then
    log "${OUT_DIR}/.deployed already exists - already deployed, nothing to do"
    exit 0
fi

mkdir -p "${WALLET_DIR}" "${OUT_DIR}/tx" "${OUT_DIR}/datums" "${OUT_DIR}/redeemers"
cd "${WORK_DIR}"

# --- JWT signing key ---------------------------------------------------------
# Shared by vpn-indexer (signs session tokens + authenticates to the
# WireGuard container) and the wireguard container (verifies that
# signature). Independent of the chain, so do it first.
if [ ! -f "${OUT_DIR}/jwt-private.pem" ]; then
    log "generating JWT signing key"
    openssl genpkey -algorithm ed25519 -out "${OUT_DIR}/jwt-private.pem"
    openssl pkey -in "${OUT_DIR}/jwt-private.pem" -pubout -out "${OUT_DIR}/jwt-public.pem"
fi

# --- Wait for the chain to actually be producing blocks --------------------
# The node's healthcheck (socket exists) can pass before genesis's
# systemStart; querying the tip fails cleanly until then.
log "waiting for the node to come up and start the chain"
for _ in $(seq 1 120); do
    if cardano-cli query tip ${MAGIC_ARG} >/dev/null 2>&1; then
        break
    fi
    sleep 5
done
cardano-cli query tip ${MAGIC_ARG}

# --- Locate a funded genesis address ---------------------------------------
find_funded_genesis_address() {
    local addr_info addr idx skey utxo_file
    utxo_file="$(mktemp)"
    for addr_info in "${GENESIS_DIR}"/genesis.*.addr.info; do
        [ -e "${addr_info}" ] || continue
        addr=$(jq -r .address "${addr_info}")
        idx="${addr_info##*/genesis.}"
        idx="${idx%.addr.info}"
        skey="${GENESIS_DIR}/genesis.${idx}.skey"
        cardano-cli query utxo ${MAGIC_ARG} --address "${addr}" --out-file "${utxo_file}" 2>/dev/null || continue
        if [ "$(jq 'length' "${utxo_file}")" -gt 0 ]; then
            echo "${addr}" "${skey}"
            rm -f "${utxo_file}"
            return 0
        fi
    done
    rm -f "${utxo_file}"
    return 1
}

log "looking for a funded genesis address"
FUNDER_INFO=""
for _ in $(seq 1 60); do
    if FUNDER_INFO=$(find_funded_genesis_address); then
        break
    fi
    sleep 5
done
if [ -z "${FUNDER_INFO}" ]; then
    log "no funded genesis address found after waiting"
    exit 1
fi
read -r FUNDER_ADDR FUNDER_SKEY <<<"${FUNDER_INFO}"
log "funding from genesis address ${FUNDER_ADDR}"

# --- Generate test wallets ---------------------------------------------------
gen_wallet() {
    local name=$1
    cardano-cli address key-gen \
        --verification-key-file "${WALLET_DIR}/${name}.vkey" \
        --signing-key-file "${WALLET_DIR}/${name}.skey"
    cardano-cli conway stake-address key-gen \
        --verification-key-file "${WALLET_DIR}/${name}-stake.vkey" \
        --signing-key-file "${WALLET_DIR}/${name}-stake.skey"
    cardano-cli conway stake-address build \
        ${MAGIC_ARG} \
        --stake-verification-key-file "${WALLET_DIR}/${name}-stake.vkey" \
        --out-file "${WALLET_DIR}/${name}-stake.addr"
    cardano-cli address build \
        ${MAGIC_ARG} \
        --payment-verification-key-file "${WALLET_DIR}/${name}.vkey" \
        --stake-verification-key-file "${WALLET_DIR}/${name}-stake.vkey" \
        --out-file "${WALLET_DIR}/${name}.addr"
}

for w in provider reference user1 user2 user3; do
    log "generating wallet: ${w}"
    gen_wallet "${w}"
done

# --- Fund the test wallets from the genesis address -------------------------
log "funding test wallets from genesis"
# 1,000 ADA each: comfortable for fees/collateral/min-UTxO, but *not* huge -
# genesis's own initial-funds UTxO (one pool -> ~100-200k ADA total, split
# across a staked and unstaked address) has to cover all five in one go.
FUND_LOVELACE=1000000000
FUNDER_UTXO_FILE=$(mktemp)
cardano-cli query utxo ${MAGIC_ARG} --address "${FUNDER_ADDR}" --out-file "${FUNDER_UTXO_FILE}"
FUNDER_TXIN=$(jq -r 'to_entries | max_by(.value.value.lovelace) | .key' "${FUNDER_UTXO_FILE}")

BUILD_ARGS=(conway transaction build ${MAGIC_ARG} --tx-in "${FUNDER_TXIN}" --change-address "${FUNDER_ADDR}")
for w in provider reference user1 user2 user3; do
    BUILD_ARGS+=(--tx-out "$(cat "${WALLET_DIR}/${w}.addr")+${FUND_LOVELACE}")
done
BUILD_ARGS+=(--out-file "${OUT_DIR}/tx/fund.raw")
cardano-cli "${BUILD_ARGS[@]}"
cardano-cli conway transaction sign \
    --tx-body-file "${OUT_DIR}/tx/fund.raw" \
    --signing-key-file "${FUNDER_SKEY}" \
    ${MAGIC_ARG} \
    --out-file "${OUT_DIR}/tx/fund.sign"
cardano-cli conway transaction submit ${MAGIC_ARG} --tx-file "${OUT_DIR}/tx/fund.sign"

wait_for_balance() {
    local addr=$1 out
    out=$(mktemp)
    for _ in $(seq 1 60); do
        cardano-cli query utxo ${MAGIC_ARG} --address "${addr}" --out-file "${out}" 2>/dev/null || true
        if [ "$(jq 'length' "${out}" 2>/dev/null || echo 0)" -gt 0 ]; then
            rm -f "${out}"
            return 0
        fi
        sleep 5
    done
    rm -f "${out}"
    log "wallet at ${addr} never received funds"
    exit 1
}
for w in provider reference user1 user2 user3; do
    log "waiting for ${w} to be funded"
    wait_for_balance "$(cat "${WALLET_DIR}/${w}.addr")"
done

# --- Apply the nft policy's output_reference parameter ----------------------
# The admin/reference NFT is minted by spending a specific UTxO, and the nft
# validator is parameterized by *that exact* output reference so the policy
# can only ever mint once. Pick provider's funding UTxO now, apply it, and
# spend that same UTxO (and no other) in the mint below.
PROVIDER_ADDR=$(cat "${WALLET_DIR}/provider.addr")
PROVIDER_UTXO_FILE=$(mktemp)
cardano-cli query utxo ${MAGIC_ARG} --address "${PROVIDER_ADDR}" --out-file "${PROVIDER_UTXO_FILE}"
NFT_SEED_TXIN=$(jq -r 'to_entries | max_by(.value.value.lovelace) | .key' "${PROVIDER_UTXO_FILE}")
NFT_SEED_HASH="${NFT_SEED_TXIN%#*}"
NFT_SEED_IDX="${NFT_SEED_TXIN#*#}"
log "nft policy output_reference: ${NFT_SEED_TXIN}"

OUTPUT_REF_JSON=$(jq -n --arg h "${NFT_SEED_HASH}" --argjson i "${NFT_SEED_IDX}" \
    '{constructor:0, fields:[{bytes:$h},{int:$i}]}')
OUTPUT_REF_CBOR=$(echo "${OUTPUT_REF_JSON}" | python3 "${WORK_DIR}/plutus_json_to_cbor.py" -)
aiken blueprint apply -m nft -v nft --in "${BLUEPRINT}" --out "${BLUEPRINT}" "${OUTPUT_REF_CBOR}"
aiken blueprint convert -m nft -v nft --to cardano-cli >"${WALLET_DIR}/../nft.plutus"
NFT_PLUTUS="${WALLET_DIR}/../nft.plutus"
NFT_CS=$(cardano-cli hash script --script-file "${NFT_PLUTUS}")
log "NFT_CS: ${NFT_CS}"

# --- Apply the vpn policy's parameters ---------------------------------------
# wait_time, then reference_policy_id, then provider_address - applied in
# validator declaration order (validators/vpn.ak).
WAIT_TIME_CBOR=$(jq -n --argjson n "${WAIT_TIME_MS}" '{int:$n}' | python3 "${WORK_DIR}/plutus_json_to_cbor.py" -)
aiken blueprint apply -m vpn -v vpn --in "${BLUEPRINT}" --out "${BLUEPRINT}" "${WAIT_TIME_CBOR}"

REF_POLICY_CBOR=$(jq -n --arg b "${NFT_CS}" '{bytes:$b}' | python3 "${WORK_DIR}/plutus_json_to_cbor.py" -)
aiken blueprint apply -m vpn -v vpn --in "${BLUEPRINT}" --out "${BLUEPRINT}" "${REF_POLICY_CBOR}"

PROVIDER_PKH=$(cardano-cli address key-hash --payment-verification-key-file "${WALLET_DIR}/provider.vkey")
PROVIDER_STAKE_KH=$(cardano-cli conway stake-address key-hash --stake-verification-key-file "${WALLET_DIR}/provider-stake.vkey")
# Address { payment_credential: VerificationKey(pkh), stake_credential: Some(Inline(VerificationKey(stake_kh))) }
PROVIDER_ADDR_JSON=$(jq -n --arg pkh "${PROVIDER_PKH}" --arg skh "${PROVIDER_STAKE_KH}" '
  {constructor:0, fields:[
    {constructor:0, fields:[{bytes:$pkh}]},
    {constructor:0, fields:[
      {constructor:0, fields:[
        {constructor:0, fields:[{bytes:$skh}]}
      ]}
    ]}
  ]}')
PROVIDER_ADDR_CBOR=$(echo "${PROVIDER_ADDR_JSON}" | python3 "${WORK_DIR}/plutus_json_to_cbor.py" -)
aiken blueprint apply -m vpn -v vpn --in "${BLUEPRINT}" --out "${BLUEPRINT}" "${PROVIDER_ADDR_CBOR}"

aiken blueprint convert -m vpn -v vpn --to cardano-cli >"${WALLET_DIR}/../vpn.plutus"
VPN_PLUTUS="${WALLET_DIR}/../vpn.plutus"
VPN_CS=$(cardano-cli hash script --script-file "${VPN_PLUTUS}")
log "VPN_CS: ${VPN_CS}"

VPN_ADDR=$(cardano-cli address build \
    ${MAGIC_ARG} \
    --payment-script-file "${VPN_PLUTUS}" \
    --stake-verification-key-file "${WALLET_DIR}/provider-stake.vkey")
log "VPN_ADDR: ${VPN_ADDR}"

# --- Mint the admin/reference NFT, in the same tx as the reference script --
REF_DATA_DATUM=$(jq -n --argjson price "${PRICE_LOVELACE}" --argjson dur "${DURATION_MS}" \
    --arg region "${REGION_HEX}" --arg region2 "${OPENVPN_REGION_HEX}" '
  {constructor:0, fields:[
    {list:[{constructor:0, fields:[{int:$dur},{int:$price}]}]},
    {list:[{bytes:$region},{bytes:$region2}]}
  ]}')
echo "${REF_DATA_DATUM}" >"${OUT_DIR}/datums/vpn_reference_data.json"

REFERENCE_ADDR=$(cat "${WALLET_DIR}/reference.addr")
NFT_ASSET_NAME_HEX="70726f7669646572" # "provider"

cardano-cli conway transaction build \
    ${MAGIC_ARG} \
    --tx-in-collateral "${NFT_SEED_TXIN}" \
    --tx-in "${NFT_SEED_TXIN}" \
    --mint "1 ${NFT_CS}.${NFT_ASSET_NAME_HEX}" \
    --mint-script-file "${NFT_PLUTUS}" \
    --mint-redeemer-value '"provider"' \
    --change-address "${PROVIDER_ADDR}" \
    --tx-out "${VPN_ADDR}+2000000+1 ${NFT_CS}.${NFT_ASSET_NAME_HEX}" \
    --tx-out-inline-datum-file "${OUT_DIR}/datums/vpn_reference_data.json" \
    --tx-out "${REFERENCE_ADDR}+15830630" \
    --tx-out-reference-script-file "${VPN_PLUTUS}" \
    --out-file "${OUT_DIR}/tx/nft.raw"
cardano-cli conway transaction sign \
    ${MAGIC_ARG} \
    --tx-body-file "${OUT_DIR}/tx/nft.raw" \
    --signing-key-file "${WALLET_DIR}/provider.skey" \
    --out-file "${OUT_DIR}/tx/nft.sign"
# Some cardano-cli versions print a bare hex hash, others wrap it as
# `{"txhash": "..."}` - handle both.
NFT_TX_HASH=$(cardano-cli conway transaction txid --tx-file "${OUT_DIR}/tx/nft.sign")
if [[ "${NFT_TX_HASH}" == \{* ]]; then
    NFT_TX_HASH=$(echo "${NFT_TX_HASH}" | jq -r .txhash)
fi
cardano-cli conway transaction submit ${MAGIC_ARG} --tx-file "${OUT_DIR}/tx/nft.sign"
log "admin NFT mint tx: ${NFT_TX_HASH}"

log "waiting for the reference data UTxO to land at ${VPN_ADDR}"
wait_for_balance "${VPN_ADDR}"

SCRIPT_REF_INPUT="${NFT_TX_HASH}#1"
REFERENCE_TOKEN="${NFT_CS}.${NFT_ASSET_NAME_HEX}"

# --- Publish everything vpn-indexer needs -----------------------------------
cat >"${OUT_DIR}/vpn-indexer.env" <<EOF
INDEXER_NETWORK=devnet
INDEXER_NETWORK_MAGIC=${TESTNET_MAGIC}
INDEXER_SCRIPT_ADDRESS=${VPN_ADDR}
INDEXER_REFERENCE_TOKEN=${REFERENCE_TOKEN}
INDEXER_INTERSECT_SLOT=0
INDEXER_INTERSECT_HASH=
TXBUILDER_PROVIDER_ADDRESS=${PROVIDER_ADDR}
TXBUILDER_SCRIPT_REF_INPUT=${SCRIPT_REF_INPUT}
EOF
log "wrote ${OUT_DIR}/vpn-indexer.env"

# Fixture data for the e2e suite's mock CIP-30 wallet: a funded address plus
# its signing key for each test user, and the region/price/duration this
# deployment actually offers (the frontend reads /api/refdata for these at
# runtime, but the test needs them up front to drive the UI). user3 and
# openvpn.* exist solely for signup-flow-dual-protocol.spec.ts's OpenVPN
# leg - a dedicated wallet so it never contends for the same UTxO as
# user1's concurrent wireguard-leg signup. indexerUrl is the OpenVPN-mode
# vpn-indexer's own in-cluster Service address (testnet.sh's
# apply_vpn_indexer_openvpn) - a plain ClusterIP DNS name, known and
# reachable ahead of time since the e2e Job runs inside the same cluster/
# namespace, unlike the old two-cluster hybrid design this replaced.
cat >"${OUT_DIR}/e2e-fixtures.json" <<EOF
{
  "region": "us east-1",
  "priceLovelace": ${PRICE_LOVELACE},
  "durationMs": ${DURATION_MS},
  "users": {
    "user1": {"address": "$(cat "${WALLET_DIR}/user1.addr")"},
    "user2": {"address": "$(cat "${WALLET_DIR}/user2.addr")"},
    "user3": {"address": "$(cat "${WALLET_DIR}/user3.addr")"}
  },
  "openvpn": {"region": "${OPENVPN_REGION}", "indexerUrl": "http://vpn-indexer-openvpn:8080"}
}
EOF
log "wrote ${OUT_DIR}/e2e-fixtures.json"

touch "${OUT_DIR}/.deployed"
log "done"
